### ISSUE TITLE
Determining the completeness of the transcriptome

### ISSUE THREAD

**Issue by sr320** [sr320/paper-pano-go#12]
We should also compare the transcriptome to related species with complete genomes and/or leverage OrthoDB to assess how "complete" the transcriptome is. 

examples 
- http://journal.frontiersin.org/article/10.3389/fphys.2013.00180/full#h3
- http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0133053#sec002
- http://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12052/full

**Comment by mdelrio1** [comment]
@sr320.  Ok...(?), all check the papers and see how to do the comparison (at least understand it).

**Comment by sr320** [comment]
Steven will look for CEGMA and see if that is good option for looking on completeness
