### ISSUE TITLE
Trinity assembly parameters

### ISSUE THREAD

**Issue by mdelrio1** [sr320/paper-pano-go#13]
@sr320 Hi Steven, I couldn't find the Trinity parameters, in order to place them in the manuscript. Could you please tell me where they are. thanks

**Comment by sr320** [comment]
The code was as follows

```
Trinity.pl
--seqType fq
--JM 24G
--left /Volumes/web/cnidarian/Geo_Pool_F_GGCTAC_L006_R1_001_val_1.fq /Volumes/web/cnidarian/Geo_Pool_M_CTTGTA_L006_R1_001_val_1.fq
--right /Volumes/web/cnidarian/Geo_Pool_F_GGCTAC_L006_R2_001_val_2.fq /Volumes/web/cnidarian/Geo_Pool_M_CTTGTA_L006_R2_001_val_2.fq
--CPU 16
```

There are no special parameters - just memory and CPU allocation, maybe could just say default parameters?

**Comment by mdelrio1** [comment]
Excellent, thanks, yes, we'll add the default parameters.

**Comment by mdelrio1** [comment]
should we close this issue?

**Comment by sr320** [comment]
Yes
