### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by mdelrio1** [sr320/paper-pano-go#18]
@sr320 Hi Steven.
I was checking the file Panopea_Dheilly_gameto-matches.xlsx in order to find other interesting genes, and found 11 repeated contigs (f. i.  comp142462_c0_seq1, which by the way is also similar to comp142462_c1_seq1= Sperm-associated antigen involved in sperm motility), which would leave 161, instead of 172 sequences, should I look for more repeated sequences or leave as the file you uploaded.

**Comment by sr320** [comment]
Given how this was generating - blasting all Panopea contigs to Dheilly this would be expected. I think it is fine to leave in as these could be different isoforms, homologs. 
Related it would be worth determining how trinity labels contigs. comp versus c versus seq.

**Comment by mdelrio1** [comment]
@sr320 Thanks I'll check trinity labelling.
