### ISSUE TITLE
access to edit methods section

### ISSUE THREAD

**Issue by paolabatta** [sr320/paper-pano-go#19]
Hello:

I was trying to update the SNP section in the methods and I couldn't edit it,  it said i need it to pull request
so it would be great if I can get some sort of contributor access to start adding things to the methods section.
I plan on working on Steve suggestions:
One good place to start with SNPs is to take SAM file from Trinity assembly - https://github.com/sr320/paper-pano-go/wiki/Raw-Data#trinity-output
and use Samtools to create VCF file. See http://www.htslib.org/doc/samtools.html
**however I dont know how to get samtools to work**
    How can I download SAMtools into Git hub?
    how can I get access to be a writter in the github repository

**Comment by sr320** [comment]
I have added you as a collaborator so you should be able to directly edit now.

**Comment by sr320** [comment]
Re samtools, you would need to download on you Mac and run at the command-line
http://www.htslib.org/

The other option would be to run samtools in Cyverse (formerly IPlant)
