### ISSUE TITLE
Database files! help

### ISSUE THREAD

**Issue by JaviRobles** [sr320/paper-pano-go#21]
@clareliza   @sr320 Hi Steven!

We are looking for the databases to do expression analyses betwen male and female  and stage. But cannot find the database to work with.

We hope you can help us.

greetings

**Comment by sr320** [comment]
I might have to generate those files again. I will check and let you know.
thanks

**Comment by JaviRobles** [comment]
Thanks a lot!

**Comment by sr320** [comment]
I have added a CSV file 
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/paper-pano-go_Male-v-Female-Expression_csv_at_master_·_sr320_paper-pano-go_1C8F1B19.png" alt="paper-pano-go_Male-v-Female-Expression_csv_at_master_·_sr320_paper-pano-go_1C8F1B19.png"/>

direct link: https://github.com/sr320/paper-pano-go/blob/master/data-results/Male-v-Female-Expression.csv?raw=true

This has number of reads from each library.

**Comment by mdelrio1** [comment]
Thanks @sr320
