### ISSUE TITLE
Reproduction genes

### ISSUE THREAD

**Issue by mdelrio1** [sr320/paper-pano-go#22]
@sr320 Hi Steven
I'm checking for the reproduction genes, when you ran the 
../jupyter-nbs/01.2-Geo-Trans-annotation.ipynb, 
you found 222  sequences related with reproduction, however I only found 9. So I went back and found them, they "got lost" when I obtained the "unique" genes. 
Could you please upload the file, 
analyses/Geoduck_v2_blastn-NT.out

so I could work with them and check whether they are the same with Dheilly database.
Thanks

**Comment by sr320** [comment]
It is in the repository already... 

https://github.com/sr320/paper-pano-go/tree/master/jupyter-nbs/analyses

**Comment by mdelrio1** [comment]
@sr320 Thanks, I´ll check them
