### ISSUE TITLE
Other biological processes

### ISSUE THREAD

**Issue by mdelrio1** [sr320/paper-pano-go#23]
@sr320 Steven
Should we remove the other biological process (and other metabolic processes) from the annotation fig.

<img src= "https://github.com/sr320/paper-pano-go/blob/master/manuscript/figures/Panopea_annotationNoduplicatesnorbacteria.png?raw=true"  width = 75%>

 as in one of your papers (Timmins-Schiffman et al. 2013)?
If so, it would stay as

<img src= "https://github.com/sr320/paper-pano-go/blob/master/manuscript/figures/Panopea_annotationNoduplicatesnorbacteriaNoother.png?raw=true"width = 75%>

I can also leave total number of sequences instead of %.

**Comment by sr320** [comment]
I would say so - as you have noticed this is what I would commonly do

**Comment by mdelrio1** [comment]
Ok

**Comment by lacroix54** [comment]
I have a little difference in the sequences, i took the file "Geoduck-tranv3-blastx_sprot.sorted" and summit in SQLshare, eliminated the duplicates and separated the contigs. I have 16451 contigs that correspond to unique contigs in aspect P (biological process). 
@sr320 @mdelrio1 do i have the correct file?
