### ISSUE TITLE
CpG again!!

### ISSUE THREAD

**Issue by lafarga13** [sr320/paper-pano-go#25]
@sr320 

Hi Steven!!!
Finally I am trying to reproduce what you did in the 05-Geoduck-CpG.ipynb and perl is running in the new computer using Anaconda.

but my jupiter does not recognize this command lines (from 84 step)

import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

What Should I do to run does commands?

this is the message I got…

---

AttributeError                            Traceback (most recent call last)
<ipython-input-24-af55e7023913> in <module>()
----> 1 import pandas as pd

/Users/miguelangeldelrio/anaconda/lib/python3.5/site-packages/pandas/**init**.py in <module>()
     42 import pandas.core.config_init
     43 
---> 44 from pandas.core.api import *
     45 from pandas.sparse.api import *
     46 from pandas.stats.api import *

/Users/miguelangeldelrio/anaconda/lib/python3.5/site-packages/pandas/core/api.py in <module>()
      7 from pandas.core.common import isnull, notnull
      8 from pandas.core.categorical import Categorical
----> 9 from pandas.core.groupby import Grouper
     10 from pandas.core.format import set_eng_float_format
     11 from pandas.core.index import Index, CategoricalIndex, Int64Index, Float64Index, MultiIndex

/Users/miguelangeldelrio/anaconda/lib/python3.5/site-packages/pandas/core/groupby.py in <module>()
     15 from pandas.core.base import PandasObject
     16 from pandas.core.categorical import Categorical
---> 17 from pandas.core.frame import DataFrame
     18 from pandas.core.generic import NDFrame
     19 from pandas.core.index import Index, MultiIndex, CategoricalIndex, _ensure_index

/Users/miguelangeldelrio/anaconda/lib/python3.5/site-packages/pandas/core/frame.py in <module>()
     39                                    create_block_manager_from_arrays,
     40                                    create_block_manager_from_blocks)
---> 41 from pandas.core.series import Series
     42 from pandas.core.categorical import Categorical
     43 import pandas.computation.expressions as expressions

/Users/miguelangeldelrio/anaconda/lib/python3.5/site-packages/pandas/core/series.py in <module>()
     33 from pandas.core.internals import SingleBlockManager
     34 from pandas.core.categorical import Categorical, CategoricalAccessor
---> 35 import pandas.core.strings as strings
     36 from pandas.tseries.common import (maybe_to_datetimelike,
     37                                    CombinedDatetimelikeProperties)

AttributeError: module 'pandas' has no attribute 'core'

**Comment by mdelrio1** [comment]
@lafarga13 @sr320 
Faby 
close all notebooks, stop the terminal (Ctrl-C), close the terminal session and then anaconda.
open a new terminal window and run
a) conda install pandas
b) conda install -c https://conda.anaconda.org/anaconda biopython
this last one installs biopython.
After installation run anaconda and then the notebook, if this does not work, we'll see it tomorrow.

**Comment by lafarga13** [comment]
no quizo correrlo al final :-1:

**Comment by lafarga13** [comment]
so, how to install pandas ???

**Comment by lafarga13** [comment]
Logre usar pandas pero en Wakari!!!! no pude desde anaconda

**Comment by mdelrio1** [comment]
@sr320 @lafarga13 
Steven, sorry I couldn't find the file 'analyses/Geoduck-transcriptome-v2_CpG-GOSlim.tab'
from the 05-Geoduck-CpG.ipynb. 
I think I have mange to reproduce the CpG data using biopython and I would like to compare the results.
I uploaded a notebook with the information in my repository
https://github.com/mdelrio1/mdelrio-panopea1/blob/master/CpG-Geo.ipynb
It may need some clean up, but I think it gives the results we need,
I'll check tomorrow with Fabiola her problem with pandas
Thank you 
Miguel

**Comment by lafarga13** [comment]
@sr320 
I already upload the files Geoduck-transcriptome-v2_CpG-GOSlim.tab (all sequences)
Geoduck-transcriptome-v3_CpG-GOSlim.tab (without bacteria)

I didn´t see to much changes..
