### ISSUE TITLE
Unique contigs function

### ISSUE THREAD

**Issue by mdelrio1** [sr320/paper-pano-go#27]
@sr320 @lacroix54 
Hi, 
I have uploaded a notebook and two files
09-Geo-uniprotfunctions-Final.ipynb
paper-pano-go/data-results/female_protein_names-function.csv
paper-pano-go/data-results/male_protein_names-function.csv
with proteins functions obtained from the UniProt database. 
Some proteins do not have a function in the database, we need to check somewhere else.

I'm also trying to condense all information in one file, but still thinking how much and how. 
I was thinking in a csv file, is this fine?

**Comment by sr320** [comment]
Yes a csv file would be great.
