### ISSUE TITLE
Accession numbers for NGS data

### ISSUE THREAD

**Issue by sr320** [sr320/paper-pano-go#28]
We need to incorporate into manuscript

BioProject: PRJNA316216 - http://www.ncbi.nlm.nih.gov/bioproject/PRJNA316216

Study: SRP072283 - http://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP072283

Study (I think this is the link we want): SRP072283 - http://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP072283

Female Pool Experiment: SRX1659865 - http://www.ncbi.nlm.nih.gov/sra/SRX1659865

Male Pool Experiment: SRX1659865 - http://www.ncbi.nlm.nih.gov/sra/SRX1659866

**Comment by mdelrio1** [comment]
@sr320 Done, I'm working (slower than wanted) but have not updated the docs. Let you know.
