### ISSUE TITLE
super interested (SNPs section?)

### ISSUE THREAD

**Issue by paolabatta** [sr320/paper-pano-go#5]
Hola Steven:
I hope you had a good trip back, I had a great time in CT, I arrived last night and I'm getting back into the swing of things. 
I will be interested in collaborating, maybe with the SNP section or with CPG. However I want to make sure I understand how it all works. I will be submitting my text and methodology to this repository. And so far you had put in examples of what type of text and methods you want to include in this manuscript?
I look forward to getting some feedback and guidance on the direction of this manuscript.

Saludos!

**Comment by sr320** [comment]
Hola Paola!
Yes- that is the idea, that we would just collaborate using this repository. We would commit new material as generated. Could either edit online via GitHub or locally, making sure to commit and sync :+1: .

I experimented a bit today with the pull request model (we might have covered that after you left). I think that might be too complicated for most so I will add interested folks as collaborators so the can edit without `pull requests` and `merges`.

**Comment by JaviRobles** [comment]
**Hello!**
Also I am interested, I share the idea of Paola.
I like to read and learn more about all this new landscape for me; if you could provide me essential articles for all this, it would be helpful.
I will also be on the lookout for what happens to it.

Greetings!

**Comment by sr320** [comment]
One good place to start with SNPs is to take SAM file from Trinity assembly - https://github.com/sr320/paper-pano-go/wiki/Raw-Data#trinity-output

and use Samtools to create VCF file.  See http://www.htslib.org/doc/samtools.html

**Comment by paolabatta** [comment]
Im on it!

Dra.Paola G. Batta Lona
Departamento de Biotecnologia Marina
CICESE
pbatta@cicese.mx
Tel:+52 (646) 1750500, ext 27164
Carretera Ensenada-Tijuana No. 3918,
Zona Playitas, C.P. 22860,
Ensenada, B.C. Mexico,

**Comment by lacroix54** [comment]
Hi Steven,

I'm interested too, so, i want to work with the part of annotation. But, first I need to integrate all that you taught us, and i plan to work with Dr. Miguel and Dra. Fabiola, and here i'll be commenting the progress and my queries.

Saludos,
Carmen

**Comment by sr320** [comment]
I will go ahead and close this specific issue, but please add new issue as questions arise.. :fire_engine:
