### ISSUE TITLE
Need details of individuals used in sequencing

### ISSUE THREAD

**Issue by sr320** [sr320/paper-pano-go#6]
![sample_submission_ _geoduck_gonad_for_rna-seq___sam_s_notebook](https://cloud.githubusercontent.com/assets/4442039/10806819/120a2cee-7d96-11e5-96d2-48cd5a4cd833.png)

Hi @grace-ac,
We are trying to get details of the individuals used for sequencing. Could you provide a few sentences or table describing the stages? Histology pics from each would also be great - thanks

**Comment by grace-ac** [comment]
Hello @sr320 !
I just made an excel spreadsheet with links to pictures, but I need permission to post documents here... or I can just email it to you.

**Comment by grace-ac** [comment]
Sent an email instead!

**Comment by grace-ac** [comment]
Hello Steven!! Here's a spreadsheet with descriptions and links to pictures
- I hope it works. Or, I can put it in a different format if you prefer.

**Comment by sr320** [comment]
Thanks @grace-ac - email did not work, can you just put on eagle and drop url here? I have also "added" you so you should be able to attach files here...

**Comment by grace-ac** [comment]
Okay! I hope this workshttp://eagle.fish.washington.edu/scaphapoda/Grace/SeqGeoducks_StageInformation/Geoduck_SeqIndividuals_StageInfo.xlsx

**Comment by mdelrio1** [comment]
Hi Steven and Grace, 
I could download the file, thank you.
(I just modified the link to 
http://eagle.fish.washington.edu/scaphapoda/Grace/SeqGeoducks_StageInformation/Geoduck_SeqIndividuals_StageInfo.xlsx)

**Comment by sr320** [comment]
Here is snapshot

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Geoduck_SeqIndividuals_StageInfo_xlsx_1BF26834.png" alt="Geoduck_SeqIndividuals_StageInfo_xlsx_1BF26834.png"/>

**Comment by sr320** [comment]
I am going to add the description of stage in methods text.
