### ISSUE TITLE
Compile list of genes and gene sets to look for in transcriptome

### ISSUE THREAD

**Issue by sr320** [sr320/paper-pano-go#8]
We talked about looking for important genes in the transcriptome. 

There are several sources for these.  Maybe we she compile these in a central location?

Possibly in this thread or create a wiki page..

**Comment by mdelrio1** [comment]
I'll work on the annotation and look for some important genes too.

**Comment by sr320** [comment]
This is a useful resource
http://figshare.com/articles/Crassostrea_gigas_male_gonad_transcriptional_data_comparison/1004464

It includes fasta file that allows (using blast) to identify genes used in Dheilly et al study "Gametogenesis in the Pacific Oyster Crassostrea gigas: A Microarrays-Based Analysis Identifies Sex and Stage Specific Genes" - also includes corresponding table for sex-specific genes and those differentially expressed through gametogenesis.

**Comment by mdelrio1** [comment]
I have downloaded the files and be able to reproduce the box plot. I'm checking the fasta file.

**Comment by sr320** [comment]
@brentners Can  you provide papers and / or genes you went over in your presentation we should look for?

**Comment by brentners** [comment]
pmarg-dmrt

pmarg-fem1-like

pmarg-foxl2
CgDsx
CgSoxH

CgFoxL2

/Crassostrea hongkongensis /transcriptome

–Tong et al. 2015

/Pinctada margaritifera /gonad transcriptome

–Teaniniuraitemoana et al. 2014, 2015

/Crassostrea gigas /gonad transcriptome

–Zhang et al. 2014

On 11/11/15 6:30 AM, Steven Roberts wrote:

> @brentners https://github.com/brentners Can you provide papers and / 
> or genes you went over in your presentation we should look for?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sr320/paper-pano-go/issues/8#issuecomment-155797533.

## 

Brent Vadopalas
Principal Research Scientist
University of Washington
School of Aquatic & Fishery Sciences
1122 NE Boat St.
Seattle WA 98105
206.685.4689

**Comment by lacroix54** [comment]
Hi @sr320 ,

I could not find those genes in the file Geoduck-transcriptome-v2-GO-Slim.csv 
my search was with the next line (for example):

carmen@carmen-pc:~/Desktop/Geoduck$ grep -i "CgFoxL2" Geoduck-transcriptome-v2-GO-Slim.csv |head |wc
      0       0       0

**Comment by sr320** [comment]
Curious  how you looked for them. Maybe the were not top hits but possibly
still homologs are present? One way to search would be to get fasta files
and blast against Geoduck database

**Comment by lacroix54** [comment]
@sr320 
I'm on it...

**Comment by mdelrio1** [comment]
@sr320 @lacroix54 
Steven, would it be possible that we can't find those genes as GO, because they are not reviewed in the uniprot database
for instance the Cg-Dsx (Doublesex protein) is in the database but it says it is Unreviewed.
http://www.uniprot.org/uniprot/A0A0D3LXK1
I agree that getting the fasta files and blast against Geoduck database, but the Pmag genes are not alone in the GeneBank (as nucleotide alone), we need to check in the sequences from the papers.
A different approach may be checking the contigs with "sex" GO, as you searched in class, and from those check the annotation and see which may be closer to the genes Brent proposed.

**Comment by sr320** [comment]
@mdelrio1 absolutely

I suggest we do this from both "directions" you mention

1) Simply use GO terms to identify subset of interesting genes
and
2) Go into papers and get fasta files.

**Comment by mdelrio1** [comment]
@sr320 I have written how to use the excel in order to get the reproduction genes 
https://github.com/mdelrio1/mdelrio-panopea1/blob/master/notes/panopea_analysis_of_goslim_without_bacteria_using_excel.md
Is this what you asked me to do? In case you need more info, let me know.

**Comment by mdelrio1** [comment]
The excel file is in
https://github.com/mdelrio1/mdelrio-panopea1/blob/master/data/Geoduck-transcriptome-v2-GO-SlimAnalisis.xlsx
